greendog/urls.py
from django.conf.urls.defaults import *
from django.conf.urls import patterns, include, url
from django.contrib import admin
from greendog import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'start.views.index'),
    url(r'^works/$', 'works.views.works'),
    url(r'^works/(?P<slug>[^\.]+)/$', 'works.views.view_work'),
    # url(r'^greendog/', include('greendog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

start/models.py
# -*-coding: utf-8-*-
from django.db import models

class IndexPage(models.Model):
    seo_title = models.CharField(max_length=500, help_text="Заголовок (Для браузеров)", blank=True)
    seo_descritption = models.TextField(help_text="Описание (Для браузеров)", blank=True)
    seo_keywords = models.TextField(help_text="Ключевые слова (Для браузеров)", blank=True)

    pos = models.CharField(max_length=500, help_text="позиция")

    menu = models.CharField(max_length=500, help_text="")
    slug = models.SlugField(unique=True, help_text="ссылка")

    title = models.CharField(max_length=500, help_text="Заголовок")
    content = models.TextField(help_text="Контент")

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['pos']

team/models.py
# -*-coding: utf-8-*-
from django.db import models
from sorl.thumbnail import ImageField
import os.path

class Person(models.Model):
    name = models.CharField(max_length=500, help_text="Имя")
    desc = models.TextField(help_text="Пост")
    photo = ImageField(upload_to='files', blank=True)

    pos = models.CharField(max_length=500, help_text="позиция")

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['pos']
        verbose_name_plural = "Люди"

works/models.py
# -*-coding: utf-8-*-
from django.db import models
from django.contrib.sites.models import Site
import datetime
from sorl.thumbnail import ImageField
import os.path

class Work(models.Model):
    seo_title = models.CharField(max_length=500, help_text="Заголовок (Для браузеров)", blank=True)
    seo_descritption = models.TextField(help_text="Описание (Для браузеров)", blank=True)
    seo_keywords = models.TextField(help_text="Ключевые слова (Для браузеров)", blank=True)

    logo = ImageField(upload_to='files', blank=True)
    poster = ImageField(upload_to='files')

    arch = models.BooleanField("Архив", default=False, help_text="Отправить это говно в архив!")

    slug = models.SlugField(unique=True, help_text="ссылка")
    title = models.CharField(max_length=500, help_text="Заголовок")
    content = models.TextField(help_text="Контент")

    date = models.DateTimeField(default=datetime.datetime.now)

    def get_absolute_url(self):
        return 'http://%s/works/%s/' % (Site.objects.get_current().domain, self.slug)

    def get_description(self):
        return self.content.split("<!--more-->")[0]

    def get_content(self):
        return self.content.split("<!--more-->")[1]

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-date']


class WorkImage(models.Model):
    title = models.CharField(max_length=500, help_text="Заголовок")
    image = ImageField(upload_to='files', blank=True)
    desc = models.TextField(help_text="Описание", blank=True)
    parent = models.ManyToManyField('works.Work', null=True, help_text="Работа", blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Картинка"

start/views.py
# -*-coding: utf-8-*-
from start.models import IndexPage
from works.models import Work
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404

def index(request):
    return render_to_response('index.html', {
        'indexpage' : IndexPage.objects.all(),
        'works' : Work.objects.all()[:1],
    })

team/views.py
# Create your views here.

works/views.py
# -*-coding: utf-8-*-
from works.models import Work
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404
from endless_pagination.decorators import page_template
from django.template import RequestContext

def works(request, extra_context=None, template=None):
    context = {
        'works' : Work.objects.filter(arch=False),
    }
    if extra_context is not None:
        context.update(extra_context)

    if request.is_ajax():
        template = "archive_page.html"
    else:
        template = "works.html"
    return render_to_response(template, context, context_instance=RequestContext(request))

def view_work(request, slug):
    return render_to_response('work.html', {
        'work' : get_object_or_404(Work, slug=slug),
        # 'work' : Work.objects.all(),
    })

templates/archive_page.html
{% load markup %}
{% load thumbnail %}
{% load endless %}
{% paginate 2 works %}

{% for item in works %}
    <div class="works-list wrap-row{% if forloop.last %} last{% endif %}">
        <div class="work-img left">
          {% thumbnail item.poster "800x450" crop="top" as im %}
            <a href="{{ item.get_absolute_url }}"><img src="{{ im.url }}"></a>
          {% endthumbnail %}
        </div>
        <div class="work-desc right">
            {% if item.logo %}
            {% thumbnail item.logo "140x80" crop="center" as im %}
              <img class="work-logo" src="{{ im.url }}">
            {% endthumbnail %}
            {% endif %}
            <h2><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></h2>
            {{ item.get_description|markdown }}
        </div>
    </div>
{% endfor %}

{% show_more %}

{#<div class="pagination">#}
    {#{% show_pages %}#}
{#</div>#}

templates/base.html
<!DOCTYPE html>
<html lang="ru-RU">
<head>
<title>{% block title %}{% endblock %}</title>
<meta charset="UTF-8" />
<meta name="author" content="Михаил Якименко" />
{% block descriptions %}
<meta name="keywords" content="" />
<meta name="description" content="" />
{% endblock %}
<link rel="stylesheet" type="text/css" media="all" href="/static/css/style.css" />
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="/static/js/jquery.scrolling-parallax.js"></script>

{% block lib %}
{% endblock %}

{% block js_code %}
{% endblock %}

<!--googlefonts-->
<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
<!--googlefonts-->
<!--[if IE]> <script> (function() { var html5 = ("abbr,article,aside,audio,canvas,datalist,details," + "figure,footer,header,hgroup,mark,menu,meter,nav,output," + "progress,section,time,video").split(','); for (var i = 0; i < html5.length; i++) { document.createElement(html5[i]); } })(); </script> <![endif]-->

<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>

<!-- header -->
<header class="header">
    <div class="logo">
        <div class="greendog">
            <h1>Green dog</h1>
            <h2>design and development</h2>
        </div>
    </div>
    {% block nav %}
    {% endblock %}
</header>
<!-- /header -->

<!-- content -->
<section class="content">
    
{% block content %}
{% endblock %}


</section>
<!-- /content -->

<script type="text/javascript">
$(function() {
    $.scrollingParallax('/static/images/para2.png', {
        bgWidth : '100%',
        bgHeight : '400%',
        bgRepeat : true,
        staticSpeed : .25,
        staticScrollLimit : false,
        reverseDirection : true
    });
});
</script>

<!-- footer -->
<footer class="footer wrap">
    asdas
</footer>
<!-- /footer -->

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% load markup %}
{% load thumbnail %}

{% block lib %}
<!-- <script language="JavaScript" type="text/javascript" src="/static/js/jquery.scrollTo.js"></script> -->
{% endblock %}

{% block js_code %}
<script type="text/javascript">
$(document).ready(function() {
  function filterPath(string) {
  return string
    .replace(/^\//,'')
    .replace(/(index|default).[a-zA-Z]{3,4}$/,'')
    .replace(/\/$/,'');
  }
  var locationPath = filterPath(location.pathname);
  var scrollElem = scrollableElement('html', 'body');

  $('a[href*=#]').each(function() {
    var thisPath = filterPath(this.pathname) || locationPath;
    if (  locationPath == thisPath
    && (location.hostname == this.hostname || !this.hostname)
    && this.hash.replace(/#/,'') ) {
      var $target = $(this.hash), target = this.hash;
      if (target) {
        var targetOffset = $target.offset().top;
        $(this).click(function(event) {
          event.preventDefault();
          $(scrollElem).animate({scrollTop: targetOffset}, 800, function() {
            location.hash = target;
          });
        });
      }
    }
  });

  // use the first element that is "scrollable"
  function scrollableElement(els) {
    for (var i = 0, argLength = arguments.length; i <argLength; i++) {
      var el = arguments[i],
          $scrollElement = $(el);
      if ($scrollElement.scrollTop()> 0) {
        return el;
      } else {
        $scrollElement.scrollTop(1);
        var isScrollable = $scrollElement.scrollTop()> 0;
        $scrollElement.scrollTop(0);
        if (isScrollable) {
          return el;
        }
      }
    }
    return [];
  }

});
</script>
{% endblock %}

{% block nav %}
<nav class="nav-site">
    <ul class="nav-site-list" id="nav-site">
        <li><a href="#works">Works</a></li>
        {% for item in indexpage %}
        <li><a href="#{{ item.slug }}">{{ item.menu }}</a></li>
        {% endfor %}
        <li><a href="#contact">Contact</a></li>
    </ul>
</nav>
{% endblock %}

{% block content %}

<div id="works" class="index-block wrap-row">
    <h1>Our works</h1>
    {% for item in works %}

        <div class="work-img left">
          {% thumbnail item.poster "800x450" crop="top" as im %}
            <a href="{{ item.get_absolute_url }}"><img src="{{ im.url }}"></a>
          {% endthumbnail %}
        </div>
        <div class="work-desc right">
            {% if item.logo %}
            {% thumbnail item.logo "140x80" crop="center" as im %}
              <img class="work-logo" src="{{ im.url }}">
            {% endthumbnail %}
            {% endif %}
            <h2><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></h2>
            {{ item.get_description|markdown }}
        </div>

    {% endfor %}
    <div class="all-works"><a href="/works/">All projects</a></div>
</div>

{% for item in indexpage %}
    <div id="{{ item.slug }}" class="index-block">
    <h1>{{ item.title }}</h1>
    {{ item.content|markdown }}
    </div>
{% endfor %}

<div id="contact" class="index-block">
    <h1>Contact us</h1>
    asdasdasd 
    asdasd
</div>

{% endblock %}

templates/work.html
{% extends "base.html" %}

{% load markup %}
{% load thumbnail %}

{% block lib %}
<link rel="stylesheet" type="text/css" href="/static/css/jquery.lightbox-0.5.css" media="screen" />
<script type="text/javascript" src="/static/js/jquery.lightbox-0.5.js"></script>
{% endblock %}

{% block js_code %}
<script type="text/javascript">
    $(function() {
        $('#gallery a').lightBox();
    });
</script>
{% endblock %}

{% block nav %}
<nav class="nav-site">
    <ul class="nav-site-list" id="nav-site">
        <li><a href="/">Home</a></li>
    </ul>
</nav>
{% endblock %}

{% block content %}
<div class="work-sinlge">
    <h1>{{ work.title }}</h1>
    {% if work.get_content > 1%}
    {{ work.get_content|markdown }}
    {% else %}
    {{ work.content|markdown }}
    {% endif %}
    <div id="gallery" class="gallery">
        <ul>
        {% for photo in work.workimage_set.all %}
        {% thumbnail photo.image "x500" as big %}
            {% thumbnail photo.image "200x120" crop="center" as small %}
            <li><a href="{{ big.url }}"><img src="{{ small.url }}"></a></li>
            {% endthumbnail %}
        {% endthumbnail %}
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/works.html
{% extends "base.html" %}

{% block lib %}
<script src="/static/js/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block nav %}
<nav class="nav-site">
    <ul class="nav-site-list" id="nav-site">
        <li><a href="/">Home</a></li>
    </ul>
</nav>
{% endblock %}

{% block content %}
<div id="works" class="index-block">
    <h1>Our works</h1>
    {% include page_template %}
</div>
{% endblock %}